/**
 * Pipeline — Issues Service
 *
 * An Issue (or Episode — same record, two formats) is a child of a Series and
 * carries the full per-stage state of one production pipeline run:
 *
 *   stages.idea         — beat sheet from the rough human seed
 *   stages.prose        — short-story draft
 *   stages.comicScript  — page/panel script (one of two parallel script stages)
 *   stages.teleplay     — scene-by-scene teleplay (the other parallel script stage)
 *   stages.comicPages   — image-gen output for each comic page's panels
 *   stages.storyboards  — image-gen + per-scene video output via CD scene runner
 *   stages.episodeVideo — final stitched episode video via CD
 *
 * Each stage record carries a status, the user-editable input, the AI output,
 * and a `lastRunId` pointer into data/runs/<runId>/ for the LLM transcript.
 *
 * Persisted to data/pipeline-issues.json.
 */

import { join } from 'path';
import { randomUUID } from 'crypto';
import { PATHS, atomicWrite, readJSONFile, ensureDir } from '../../lib/fileUtils.js';
import { createFileWriteQueue } from '../../lib/fileWriteQueue.js';
import {
  LENGTH_PROFILE_NAMES, DEFAULT_LENGTH_PROFILE,
  CUSTOM_PAGE_MIN, CUSTOM_PAGE_MAX, CUSTOM_MINUTE_MIN, CUSTOM_MINUTE_MAX,
} from '../../lib/issueLength.js';
import { sanitizeOrigin } from '../../lib/sharingOrigin.js';
import { sanitizeVisualStyleRef } from '../../lib/visualStyles.js';
import { ARC_ROLES } from '../../lib/storyArc.js';
import { isStr, trimTo } from '../../lib/storyBible.js';
import { sanitizeCoverLike } from '../../lib/renderSlot.js';
import { emitRecordUpdated } from '../sharing/recordEvents.js';
import { applyVolumeOrderedNumbers, UNSCOPED_ANCHOR } from '../../lib/pipelineIssueOrder.js';
import * as seriesSvc from './series.js';

// Lazy resolution — see series.js for context.
const statePath = () => join(PATHS.data, 'pipeline-issues.json');

// File-level write lock: serializes concurrent updateIssue / updateStage calls
// against the shared pipeline-issues.json state file so a blur-save PATCH can
// never clobber an in-flight cover-render PATCH (and vice-versa, across any
// pair of issues — not just two writes to the same issue id). CLAUDE.md:
// "simple re-entrancy guards… are fine and expected."
const queueIssueWrite = createFileWriteQueue();

export const ERR_NOT_FOUND = 'PIPELINE_ISSUE_NOT_FOUND';
export const ERR_VALIDATION = 'PIPELINE_ISSUE_VALIDATION';
export const ERR_DUPLICATE = 'PIPELINE_ISSUE_DUPLICATE';
export const ERR_SEASON_LOCKED = 'PIPELINE_ISSUE_SEASON_LOCKED';
const makeErr = (message, code) => Object.assign(new Error(message), { code });

const ISSUE_ID_RE = /^iss-[A-Za-z0-9-]+$/;

export const TITLE_MAX = 300;
export const SERIES_ID_MAX = 64;
export const SEASON_ID_MAX = 64;
// Issues fall back to position 0 when un-numbered; the cap keeps a runaway
// LLM payload from inflating the field unbounded.
export const ARC_POSITION_MAX = 9999;
export const STAGE_INPUT_MAX = 200_000;   // ~200kB — fits a long prose draft
export const STAGE_OUTPUT_MAX = 400_000;  // ~400kB — fits a long comic script
export const STAGE_NOTES_MAX = 4000;
export const ISSUES_PER_RESPONSE_MAX = 1000;

// Stage IDs are ordered for UI display; the canonical order is also the
// auto-run text-chain order (idea → prose → scripts in parallel). Comic
// pages / storyboards / episode video stages are visual and stay manual
// in MVP.
export const TEXT_STAGE_IDS = Object.freeze(['idea', 'prose', 'comicScript', 'teleplay']);
export const VISUAL_STAGE_IDS = Object.freeze(['comicPages', 'storyboards', 'episodeVideo']);
// Audio is its own category — voice-over lines + music. Feature-gated on
// series.targetFormat (only meaningful when the series ships video, not
// comic-only). Kept separate from VISUAL_STAGE_IDS so the artifact shape
// (`lines[]`, `music`) stays distinct from visual stages.
export const AUDIO_STAGE_IDS = Object.freeze(['audio']);
export const STAGE_IDS = Object.freeze([...TEXT_STAGE_IDS, ...VISUAL_STAGE_IDS, ...AUDIO_STAGE_IDS]);
// Stages exposed to voice navigation ("next stage" / "previous stage" tools)
// and the tab strip. Includes audio now that the AudioStage UI is wired.
export const NAVIGABLE_STAGE_IDS = Object.freeze([...TEXT_STAGE_IDS, ...VISUAL_STAGE_IDS, ...AUDIO_STAGE_IDS]);

// "This stage has usable content and shouldn't be regenerated by default."
// `edited` = user typed into the editor; `ready` = LLM filled and the user
// hasn't asked to rerun. Both are good — auto-runners skip past them unless
// `force` is set. Defined here so every coordinator agrees on the predicate.
export function isStageReady(stage) {
  if (!stage) return false;
  if (stage.status !== 'ready' && stage.status !== 'edited') return false;
  return !!(stage.output && stage.output.trim());
}
export const STAGE_STATUSES = Object.freeze(['empty', 'generating', 'ready', 'edited', 'needs-review', 'error']);
export const ISSUE_STATUSES = Object.freeze(['draft', 'running', 'needs-review', 'shipped']);

const emptyStage = () => ({
  status: 'empty',
  input: '',
  output: '',
  lastRunId: null,
  errorMessage: '',
  updatedAt: null,
});

const sanitizeStage = (raw) => {
  if (!raw || typeof raw !== 'object') return emptyStage();
  const status = STAGE_STATUSES.includes(raw.status) ? raw.status : 'empty';
  return {
    status,
    input: trimTo(raw.input, STAGE_INPUT_MAX),
    output: trimTo(raw.output, STAGE_OUTPUT_MAX),
    lastRunId: isStr(raw.lastRunId) && raw.lastRunId ? raw.lastRunId : null,
    errorMessage: trimTo(raw.errorMessage, STAGE_NOTES_MAX),
    updatedAt: isStr(raw.updatedAt) ? raw.updatedAt : null,
  };
};

// Episode-video render settings the user chose at kickoff time. Persisted
// on the stage so a page reload doesn't reset them to the defaults — the
// restart flow can render the same pickers populated with the user's
// previous choice. The CD project itself owns the authoritative values once
// rendering starts; these are the *requested* settings for the next start.
const ASPECT_RATIO_VALUES = new Set(['16:9', '9:16', '1:1']);
const QUALITY_VALUES = new Set(['draft', 'standard', 'high']);

// `imageMode: 'auto'` defers to the server resolver (codex when enabled,
// local otherwise). Returns null when nothing was set so the persisted
// JSON stays clean for issues that never opened the panel.
const IMAGE_MODE_VALUES = new Set(['auto', 'local', 'codex']);
const GEN_CONFIG_STR_MAX = 200;
const sanitizeGenConfig = (raw) => {
  if (!raw || typeof raw !== 'object') return null;
  const imageMode = IMAGE_MODE_VALUES.has(raw.imageMode) ? raw.imageMode : 'auto';
  // imageModelId is only meaningful for local diffusion — clear it for other
  // modes so a previously-pinned model doesn't silently persist in the config
  // and mislead the UI or any future reader that doesn't filter by mode.
  const imageModelId = imageMode === 'local'
    ? (trimTo(raw.imageModelId, GEN_CONFIG_STR_MAX) || null)
    : null;
  const refineProvider = trimTo(raw.refineProvider, GEN_CONFIG_STR_MAX) || null;
  const refineModel = trimTo(raw.refineModel, GEN_CONFIG_STR_MAX) || null;
  if (imageMode === 'auto' && !imageModelId && !refineProvider && !refineModel) {
    return null;
  }
  return { imageMode, imageModelId, refineProvider, refineModel };
};

// Page records (pages[]) are pass-through in sanitizeVisualStage's array
// slice, so the new proofImage/finalImage fields survive there without an
// explicit sanitizer. If pages ever gets a deep sanitizer, route slot
// records through sanitizeRenderSlot (lib/renderSlot.js) the same way
// the cover does.

const sanitizeVisualStage = (raw, stageId = null) => {
  // Visual stages keep arbitrary structured artifact lists. Sanitize the
  // wrapper but pass through known shapes.
  const base = sanitizeStage(raw);
  return {
    ...base,
    pages: Array.isArray(raw?.pages) ? raw.pages.slice(0, 200) : [],
    scenes: Array.isArray(raw?.scenes) ? raw.scenes.slice(0, 200) : [],
    cdProjectId: isStr(raw?.cdProjectId) && raw.cdProjectId ? raw.cdProjectId : null,
    videoPath: isStr(raw?.videoPath) && raw.videoPath ? raw.videoPath : null,
    aspectRatio: ASPECT_RATIO_VALUES.has(raw?.aspectRatio) ? raw.aspectRatio : null,
    quality: QUALITY_VALUES.has(raw?.quality) ? raw.quality : null,
    // genConfig is read by comicPages/storyboards; pass-through is a no-op on
    // episodeVideo, which never looks at it.
    genConfig: sanitizeGenConfig(raw?.genConfig),
    // `cover` and `backCover` are meaningful only on comicPages — they carry
    // the front/back-cover concept + render jobs. Dropping them on
    // storyboards / episodeVideo makes the contract explicit (matches the
    // comment in pipeline.js's visual stage schema). When stageId is
    // omitted (legacy callers / stage-shape sanitize at issue load time
    // without per-stage context), keep the field — `sanitizeStages` below
    // threads the stageId through so the canonical persistence path
    // enforces the rule.
    cover: stageId === null || stageId === 'comicPages' ? sanitizeCoverLike(raw?.cover) : null,
    backCover: stageId === null || stageId === 'comicPages' ? sanitizeCoverLike(raw?.backCover) : null,
    // Per-stage override so a series can mix aesthetics
    // (e.g. graphic-novel panels + cinematic storyboards).
    visualStyleOverride: sanitizeVisualStyleRef(raw?.visualStyleOverride),
  };
};

// Audio stage shape — dialogue VO lines + optional background music. Each
// line carries the source character + the actual line text + the render job
// id + a server-stamped filename (the storyboards filename hook's pattern
// will be extended to audio in a follow-up). `voiceIdOverride` lets a single
// line use a different voice than the character's default (narrator V.O.,
// flashback voice, etc.).
const AUDIO_LINE_TEXT_MAX = 4000;
const AUDIO_LINES_MAX = 1000;
const AUDIO_FILENAME_MAX = 500;
const AUDIO_LINE_ID_MAX = 80;
const sanitizeAudioLine = (raw, i) => {
  if (!raw || typeof raw !== 'object') return null;
  const text = trimTo(raw.text, AUDIO_LINE_TEXT_MAX);
  if (!text) return null;
  const id = trimTo(raw.id, AUDIO_LINE_ID_MAX) || `line-${String(i + 1).padStart(3, '0')}`;
  return {
    id,
    characterId: trimTo(raw.characterId, 80) || null,
    characterName: trimTo(raw.characterName, 120) || null,
    text,
    voiceIdOverride: trimTo(raw.voiceIdOverride, 200) || null,
    audioJobId: isStr(raw.audioJobId) && raw.audioJobId ? raw.audioJobId : null,
    audioFilename: isStr(raw.audioFilename) && raw.audioFilename
      ? raw.audioFilename.slice(0, AUDIO_FILENAME_MAX)
      : null,
  };
};

const MUSIC_SOURCES = new Set(['upload', 'library', 'gen']);
const sanitizeMusicTrack = (raw) => {
  if (!raw || typeof raw !== 'object') return null;
  const source = MUSIC_SOURCES.has(raw.source) ? raw.source : null;
  const trackFilename = trimTo(raw.trackFilename, AUDIO_FILENAME_MAX) || null;
  const label = trimTo(raw.label, 200) || null;
  if (!source && !trackFilename && !label) return null;
  return { source, trackFilename, label };
};

const sanitizeAudioStage = (raw) => {
  const base = sanitizeStage(raw);
  return {
    ...base,
    lines: Array.isArray(raw?.lines)
      ? raw.lines.slice(0, AUDIO_LINES_MAX).map(sanitizeAudioLine).filter(Boolean)
      : [],
    music: sanitizeMusicTrack(raw?.music),
  };
};

const sanitizeStages = (raw = {}) => {
  const out = {};
  for (const id of TEXT_STAGE_IDS) out[id] = sanitizeStage(raw[id]);
  for (const id of VISUAL_STAGE_IDS) out[id] = sanitizeVisualStage(raw[id], id);
  for (const id of AUDIO_STAGE_IDS) out[id] = sanitizeAudioStage(raw[id]);
  return out;
};

const sanitizeIssue = (raw) => {
  if (!raw || typeof raw !== 'object') return null;
  if (!isStr(raw.id) || !raw.id) return null;
  if (!isStr(raw.seriesId) || !raw.seriesId) return null;
  const title = trimTo(raw.title, TITLE_MAX);
  if (!title) return null;
  const number = Number.isFinite(raw.number) ? Math.max(0, Math.floor(raw.number)) : 0;
  const status = ISSUE_STATUSES.includes(raw.status) ? raw.status : 'draft';
  const createdAt = isStr(raw.createdAt) ? raw.createdAt : new Date().toISOString();
  const updatedAt = isStr(raw.updatedAt) ? raw.updatedAt : createdAt;
  // Phase 2 of Story Arc Planning: optional pointer back into the parent
  // series' arc tree. `null` is the back-compat default — every pre-existing
  // issue stays un-grouped until the user (or LLM-arc-generation) assigns it.
  const seasonId = isStr(raw.seasonId) && raw.seasonId
    ? trimTo(raw.seasonId, SEASON_ID_MAX)
    : null;
  const arcPosition = Number.isFinite(raw.arcPosition)
    ? Math.max(0, Math.min(ARC_POSITION_MAX, Math.floor(raw.arcPosition)))
    : null;
  // LLM-assigned role within the volume — drives beat-sheet cadence
  // (finale vs. complication need very different shapes).
  const arcRole = ARC_ROLES.includes(raw.arcRole) ? raw.arcRole : null;
  // Defaults to 'standard' so pre-field issues keep the prior 22pg/24min sizing.
  // pageTarget/minutesTarget are only consumed when lengthProfile==='custom',
  // but we persist them on every profile so the picker can remember a previous
  // custom value if the user toggles back. Bounds mirror the values
  // `computeIssueTargets` clamps to at render time — otherwise the persisted
  // record could disagree with the prompt-rendered length.
  const lengthProfile = LENGTH_PROFILE_NAMES.includes(raw.lengthProfile)
    ? raw.lengthProfile
    : DEFAULT_LENGTH_PROFILE;
  const pageTarget = Number.isFinite(raw.pageTarget)
    ? Math.max(CUSTOM_PAGE_MIN, Math.min(CUSTOM_PAGE_MAX, Math.round(raw.pageTarget)))
    : null;
  const minutesTarget = Number.isFinite(raw.minutesTarget)
    ? Math.max(CUSTOM_MINUTE_MIN, Math.min(CUSTOM_MINUTE_MAX, Math.round(raw.minutesTarget)))
    : null;
  return {
    id: raw.id,
    seriesId: trimTo(raw.seriesId, SERIES_ID_MAX),
    number,
    title,
    status,
    seasonId,
    arcPosition,
    arcRole,
    lengthProfile,
    pageTarget,
    minutesTarget,
    stages: sanitizeStages(raw.stages || {}),
    // Share-bucket provenance — present on imported records, absent on locally-authored ones.
    origin: sanitizeOrigin(raw.origin),
    createdAt,
    updatedAt,
  };
};

async function readState() {
  await ensureDir(PATHS.data);
  const raw = await readJSONFile(statePath(), { issues: [] }, { logError: false });
  const issues = Array.isArray(raw.issues) ? raw.issues.map(sanitizeIssue).filter(Boolean) : [];
  return { issues };
}

async function writeState(state) {
  await atomicWrite(statePath(), state);
}

export async function listIssues({ seriesId = null } = {}) {
  const { issues } = await readState();
  const filtered = seriesId ? issues.filter((i) => i.seriesId === seriesId) : issues;
  return [...filtered]
    .sort((a, b) => {
      if (a.seriesId !== b.seriesId) return a.seriesId.localeCompare(b.seriesId);
      return (a.number || 0) - (b.number || 0);
    })
    .slice(0, ISSUES_PER_RESPONSE_MAX);
}

/**
 * Recently-updated issues across all series. Sorts the FULL issue set by
 * `updatedAt` desc before applying `limit` — unlike `listIssues`, which
 * sorts by `seriesId/number` then caps at `ISSUES_PER_RESPONSE_MAX`. That
 * cap would silently miss the most-recent issues once the dataset grows
 * beyond 1000, so the sidebar's recent-issues view needs this dedicated
 * helper.
 */
export async function listRecentIssues({ limit = 10 } = {}) {
  const { issues } = await readState();
  // Coerce in two passes so non-finite inputs ('abc', undefined) fall to
  // the default rather than letting JS's `0 || 10` short-circuit return
  // 10 for an explicit limit=0.
  const raw = Number(limit);
  const fallback = Number.isFinite(raw) ? Math.floor(raw) : 10;
  const clamped = Math.max(1, Math.min(50, fallback));
  return [...issues]
    .sort((a, b) => (b.updatedAt || '').localeCompare(a.updatedAt || ''))
    .slice(0, clamped);
}

export async function getIssue(id) {
  const { issues } = await readState();
  const found = issues.find((i) => i.id === id);
  if (!found) throw makeErr(`Issue not found: ${id}`, ERR_NOT_FOUND);
  return found;
}

export function createIssue(input = {}) {
  const seriesId = trimTo(input.seriesId, SERIES_ID_MAX);
  if (!seriesId) return Promise.reject(makeErr('seriesId is required', ERR_VALIDATION));
  const title = trimTo(input.title, TITLE_MAX);
  if (!title) return Promise.reject(makeErr(`title is required (1..${TITLE_MAX} chars)`, ERR_VALIDATION));
  return queueIssueWrite(async () => {
  const state = await readState();
  const next = sanitizeIssue({
    id: `iss-${randomUUID()}`,
    seriesId,
    // Placeholder — `renumberInline` below derives the canonical number.
    number: 0,
    title,
    status: 'draft',
    // Phase 2: optional arc pointers passed by the season-episodes generator
    // (and any future caller wiring an issue to a season at create time).
    seasonId: 'seasonId' in input ? input.seasonId : null,
    arcPosition: 'arcPosition' in input ? input.arcPosition : null,
    arcRole: 'arcRole' in input ? input.arcRole : null,
    lengthProfile: 'lengthProfile' in input ? input.lengthProfile : undefined,
    pageTarget: 'pageTarget' in input ? input.pageTarget : null,
    minutesTarget: 'minutesTarget' in input ? input.minutesTarget : null,
    stages: input.stages || {},
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  });
  if (!next) throw makeErr('Invalid issue payload', ERR_VALIDATION);
  state.issues.push(next);
  await renumberInline(state, seriesId, next.seasonId || UNSCOPED_ANCHOR);
  await writeState(state);
  // New issue = series-level change for any active share subscription.
  emitRecordUpdated('series', next.seriesId);
  return next;
  }); // end queueIssueWrite
}

async function renumberInline(state, seriesId, fromSeasonId = null) {
  const series = await seriesSvc.getSeries(seriesId).catch(() => null);
  return applyVolumeOrderedNumbers({
    issues: state.issues,
    seriesId,
    seasons: series?.seasons || [],
    fromSeasonId,
  });
}

export function recomputeIssueNumbersForSeries(seriesId, fromSeasonId = null) {
  return queueIssueWrite(async () => {
    const state = await readState();
    const changed = await renumberInline(state, seriesId, fromSeasonId);
    if (!changed) return { changed: false };
    await writeState(state);
    emitRecordUpdated('series', seriesId);
    return { changed: true };
  });
}

/**
 * Reassign every issue under `(seriesId, fromSeasonId)` to `toSeasonId` in a
 * single readState → in-memory mutate → writeState → one renumber pass.
 * Used by `deleteSeason` (and any future bulk season-move flow) to collapse
 * N per-issue queueIssueWrite cycles into one — the legacy N+1 pattern was
 * `for (iss of children) await updateIssue(iss.id, { seasonId: toSeasonId }, { skipRenumber: true })`
 * which paid N readState + N writeState round-trips and N debounced re-exports
 * even with `withReexportSuppressed`.
 *
 * Returns `{ reassigned, fromSeasonId, toSeasonId }`. `toSeasonId` may be
 * `null` (un-grouped). A re-export of the parent series is emitted once, after
 * the renumber pass — callers under `withReexportSuppressed` get exactly one
 * `series:updated` event regardless of the issue count.
 */
export function bulkReassignSeason(seriesId, fromSeasonId, toSeasonId = null, { _preloadedSeries = null } = {}) {
  return queueIssueWrite(async () => {
    // Honor per-season locks — refuse to move issues OUT of or INTO a locked
    // volume. Series lives in a different write queue, so this is best-effort
    // single-user gating, not strict serialization (fine per CLAUDE.md).
    // Callers that already hold a fresh series (e.g. `deleteSeason` reads it
    // for the reassign-target validation) can pass `_preloadedSeries` to skip
    // the duplicate read.
    if (fromSeasonId || toSeasonId) {
      const series = _preloadedSeries || await seriesSvc.getSeries(seriesId);
      const seasons = Array.isArray(series.seasons) ? series.seasons : [];
      const findLocked = (id) => (id ? seasons.find((s) => s.id === id && s.locked === true) : null);
      const blocker = findLocked(fromSeasonId) || findLocked(toSeasonId);
      if (blocker) {
        throw makeErr(
          `Season "${blocker.title || blocker.number}" is locked — unlock it before reassigning issues`,
          ERR_SEASON_LOCKED,
        );
      }
    }
    const state = await readState();
    let reassigned = 0;
    const now = new Date().toISOString();
    for (let i = 0; i < state.issues.length; i += 1) {
      const iss = state.issues[i];
      if (iss.seriesId !== seriesId) continue;
      if ((iss.seasonId || null) !== (fromSeasonId || null)) continue;
      // Re-sanitize through the same pipeline updateIssue uses so the
      // in-memory rewrite gets the same shape guarantees as a route PATCH.
      const merged = sanitizeIssue({
        ...iss,
        seasonId: toSeasonId,
        updatedAt: now,
      });
      if (!merged) continue;
      state.issues[i] = merged;
      reassigned += 1;
    }
    if (reassigned === 0) return { reassigned: 0, fromSeasonId, toSeasonId };
    // One renumber pass after the bulk move — the source AND destination
    // volume both reshuffled, so use the series-wide form (fromSeasonId=null).
    await renumberInline(state, seriesId, null);
    await writeState(state);
    emitRecordUpdated('series', seriesId);
    return { reassigned, fromSeasonId, toSeasonId };
  });
}

/**
 * Insert an issue with a caller-supplied id (used by the share-bucket importer
 * so re-imports of the same issue LWW-merge onto the same local row).
 * Throws ERR_DUPLICATE / ERR_VALIDATION on contract violations.
 */
export function insertIssueWithId(input = {}) {
  if (!isStr(input.id) || !ISSUE_ID_RE.test(input.id)) {
    return Promise.reject(makeErr(`insertIssueWithId: invalid id "${input.id}" (expected iss-<uuid>)`, ERR_VALIDATION));
  }
  const seriesId = trimTo(input.seriesId, SERIES_ID_MAX);
  if (!seriesId) return Promise.reject(makeErr('seriesId is required', ERR_VALIDATION));
  const title = trimTo(input.title, TITLE_MAX);
  if (!title) return Promise.reject(makeErr(`title is required (1..${TITLE_MAX} chars)`, ERR_VALIDATION));
  return queueIssueWrite(async () => {
    const state = await readState();
    if (state.issues.some((i) => i.id === input.id)) {
      throw makeErr(`Issue id already exists: ${input.id}`, ERR_DUPLICATE);
    }
    const next = sanitizeIssue({ ...input, seriesId, title });
    if (!next) throw makeErr('Invalid issue payload', ERR_VALIDATION);
    state.issues.push(next);
    // Imported `number` is a starting hint — local canonical numbering still
    // comes from (volume order, arcPosition) of the local state.
    await renumberInline(state, seriesId, next.seasonId || UNSCOPED_ANCHOR);
    await writeState(state);
    return next;
  });
}

export function updateIssue(id, patch = {}, { skipRenumber = false } = {}) {
  return queueIssueWrite(async () => {
  const state = await readState();
  const idx = state.issues.findIndex((i) => i.id === id);
  if (idx < 0) throw makeErr(`Issue not found: ${id}`, ERR_NOT_FOUND);
  const cur = state.issues[idx];

  // Per-stage merge: a stage patch carries only the fields the caller is
  // changing (e.g. `{ genConfig }` or `{ cover }`). Without this, the top-level
  // spread would replace the entire stage object and silently drop sibling
  // fields like `scenes` / `pages` / `genConfig`. Sanitization then defaults
  // those back to empty arrays/null, erasing work the user (or LLM) just did.
  // Callers that need stage-level changes without touching issue-level fields
  // should use `updateStage`, which does a shallow merge of the patch over the
  // existing stage (`{ ...cur.stages[stageId], ...patch }`) before sanitizing.
  // Note: `updateStage` still merges — omitted sibling stage fields are
  // preserved. To clear a field explicitly, pass it as `null` or `""` in the
  // patch.
  //
  // `cover` and `genConfig` are treated as deep-merge sub-objects: a partial
  // `{ cover: { script } }` patch from a textarea-blur save must not wipe the
  // sibling `imageJobId` / `prompt` that a parallel "Render cover" mutation
  // just persisted. Passing `null` explicitly still clears the sub-object
  // (intentional-clear semantics).
  const NESTED_DEEP_MERGE_KEYS = ['cover', 'genConfig'];
  let mergedStages = cur.stages;
  if ('stages' in patch && patch.stages && typeof patch.stages === 'object') {
    mergedStages = { ...cur.stages };
    for (const [stageId, stagePatch] of Object.entries(patch.stages)) {
      const prev = cur.stages?.[stageId];
      if (prev && stagePatch && typeof prev === 'object' && typeof stagePatch === 'object') {
        const merged = { ...prev, ...stagePatch };
        for (const key of NESTED_DEEP_MERGE_KEYS) {
          if (key in stagePatch
              && stagePatch[key] && typeof stagePatch[key] === 'object'
              && prev[key] && typeof prev[key] === 'object') {
            merged[key] = { ...prev[key], ...stagePatch[key] };
          }
        }
        // Clear transient error fields when a content/status change implies
        // the previous failure is no longer the active state. Mirrors the
        // pre-per-stage-merge behavior, where a `{ status, input, output }`
        // patch replaced the whole stage and implicitly wiped errorMessage.
        if ('status' in stagePatch && stagePatch.status !== 'error'
            && stagePatch.status !== 'generating'
            && !('errorMessage' in stagePatch)) {
          merged.errorMessage = '';
        }
        mergedStages[stageId] = merged;
      } else {
        mergedStages[stageId] = stagePatch;
      }
    }
  }

  const merged = sanitizeIssue({
    ...cur,
    ...('title' in patch ? { title: patch.title } : {}),
    ...('number' in patch ? { number: patch.number } : {}),
    ...('status' in patch ? { status: patch.status } : {}),
    ...('seasonId' in patch ? { seasonId: patch.seasonId } : {}),
    ...('arcPosition' in patch ? { arcPosition: patch.arcPosition } : {}),
    ...('arcRole' in patch ? { arcRole: patch.arcRole } : {}),
    ...('lengthProfile' in patch ? { lengthProfile: patch.lengthProfile } : {}),
    ...('pageTarget' in patch ? { pageTarget: patch.pageTarget } : {}),
    ...('minutesTarget' in patch ? { minutesTarget: patch.minutesTarget } : {}),
    ...('origin' in patch ? { origin: patch.origin } : {}),
    stages: mergedStages,
    updatedAt: new Date().toISOString(),
  });
  if (!merged) throw makeErr('Invalid issue payload', ERR_VALIDATION);
  state.issues[idx] = merged;
  // A seasonId move affects both source and destination volumes, so full
  // renumber. An arcPosition change only reorders within the current volume.
  // `skipRenumber` lets bulk callers (e.g. deleteSeason) collapse N per-update
  // renumbers into one final pass.
  if (!skipRenumber) {
    if ('seasonId' in patch && cur.seasonId !== merged.seasonId) {
      await renumberInline(state, merged.seriesId, null);
    } else if ('arcPosition' in patch && cur.arcPosition !== merged.arcPosition) {
      await renumberInline(state, merged.seriesId, merged.seasonId || UNSCOPED_ANCHOR);
    }
  }
  await writeState(state);
  // Issues are exported as part of their parent series — re-export the
  // series so any active subscription picks up the issue change.
  emitRecordUpdated('series', merged.seriesId);
  return merged;
  }); // end queueIssueWrite
}

/**
 * Partial update to a single stage on an issue. Use this from generators so
 * a stage write doesn't have to load the full issue, mutate, and re-validate.
 * Patch keys: status, input, output, lastRunId, errorMessage, and (for
 * visual stages) pages/scenes/cdProjectId/videoPath.
 *
 * When the patch depends on the current stage value (e.g. cover preservation),
 * use `updateStageWithLatest` instead so the decision is made against the
 * freshest persisted record inside the serialized write region.
 */
export function updateStage(issueId, stageId, patch = {}) {
  return updateStageWithLatest(issueId, stageId, () => patch);
}

export function deleteIssue(id) {
  return queueIssueWrite(async () => {
  const state = await readState();
  const idx = state.issues.findIndex((i) => i.id === id);
  if (idx < 0) throw makeErr(`Issue not found: ${id}`, ERR_NOT_FOUND);
  const removed = state.issues[idx];
  const seriesId = removed.seriesId;
  state.issues.splice(idx, 1);
  await renumberInline(state, seriesId, removed.seasonId || UNSCOPED_ANCHOR);
  await writeState(state);
  // Series export bundles every issue, so a deletion is an update on the
  // parent series for any active share-bucket subscription.
  emitRecordUpdated('series', seriesId);
  return { id };
  }); // end queueIssueWrite
}

/**
 * Like `updateStage`, but the patch is computed from the *latest* persisted
 * stage inside the serialized write region. Use this when the patch value
 * depends on the current stage state (e.g. cover preservation) so a concurrent
 * write that lands between the outer `getIssue` read and this call is not
 * silently overwritten.
 *
 * `computeFn(currentStage) → patch` — called with the freshest stage record
 * inside the queue; its return value is shallow-merged over the stage exactly
 * as `updateStage` merges a static patch.
 */
export function updateStageWithLatest(issueId, stageId, computeFn) {
  if (!STAGE_IDS.includes(stageId)) {
    // Validate before queueing so the caller gets an immediate rejection
    // rather than waiting in line for an error it already knows about.
    return Promise.reject(makeErr(`Unknown stage: ${stageId}`, ERR_VALIDATION));
  }
  return queueIssueWrite(async () => {
  const state = await readState();
  const idx = state.issues.findIndex((i) => i.id === issueId);
  if (idx < 0) throw makeErr(`Issue not found: ${issueId}`, ERR_NOT_FOUND);
  const cur = state.issues[idx];
  const isVisual = VISUAL_STAGE_IDS.includes(stageId);
  const isAudio = AUDIO_STAGE_IDS.includes(stageId);
  const currentStage = cur.stages[stageId];
  const patch = computeFn(currentStage);
  // Empty-patch fast path: a computeFn that returns `{}` is a "decided not
  // to write" signal (e.g. stale media-job completion against a re-rendered
  // page). Skip the disk write + emitRecordUpdated so it doesn't trigger
  // a re-export storm in share subscriptions for late no-op events.
  if (patch && typeof patch === 'object' && !Array.isArray(patch) && Object.keys(patch).length === 0) {
    return { issue: cur, stage: currentStage };
  }
  const merged = {
    ...currentStage,
    ...patch,
    updatedAt: new Date().toISOString(),
  };
  let next;
  if (isVisual) next = sanitizeVisualStage(merged, stageId);
  else if (isAudio) next = sanitizeAudioStage(merged);
  else next = sanitizeStage(merged);
  const mergedIssue = sanitizeIssue({
    ...cur,
    stages: { ...cur.stages, [stageId]: next },
    updatedAt: new Date().toISOString(),
  });
  state.issues[idx] = mergedIssue;
  await writeState(state);
  emitRecordUpdated('series', mergedIssue.seriesId);
  return { issue: mergedIssue, stage: mergedIssue.stages[stageId] };
  }); // end queueIssueWrite
}

/**
 * Sync-orchestrator entry point. Merges a remote peer's issues array into
 * local state INSIDE `queueIssueWrite`, so the read-modify-write window can't
 * clobber (or be clobbered by) a concurrent updateIssue / updateStage /
 * cover-render PATCH running through the same queue. Each incoming record
 * passes through `sanitizeIssue` for shape enforcement (stage statuses,
 * trimmed fields, valid id format). LWW by `updatedAt`; returns
 * `{ applied, count }` where `count` is the number of issues actually
 * changed/added.
 */
export function mergeIssuesFromSync(remoteIssues) {
  if (!Array.isArray(remoteIssues)) return Promise.resolve({ applied: false, count: 0 });
  return queueIssueWrite(async () => {
    const state = await readState();
    const localById = new Map(state.issues.map((i) => [i.id, i]));
    let changed = 0;
    for (const remote of remoteIssues) {
      if (!remote || typeof remote !== 'object' || !isStr(remote.id)) continue;
      const sanitized = sanitizeIssue(remote);
      if (!sanitized) continue;
      const local = localById.get(sanitized.id);
      if (!local) {
        localById.set(sanitized.id, sanitized);
        changed++;
      } else {
        const localTs = local.updatedAt || '';
        const remoteTs = sanitized.updatedAt || '';
        if (remoteTs > localTs) {
          localById.set(sanitized.id, sanitized);
          changed++;
        }
      }
    }
    if (changed === 0) return { applied: false, count: 0 };
    state.issues = Array.from(localById.values());
    await writeState(state);
    return { applied: true, count: changed };
  });
}
